name: disposables
description: Simple library to manage objects needing to release its own resources.
version: 0.1.1
homepage: https://github.com/marcguilera/dart_disposables
author: marcguilera <marcguilerap@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  quiver: ^2.0.1

dev_dependencies:
  test: ^1.0.0
